name: scholar_mind
description: AI-powered study companion for college students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  openai_dart: ^6.2.0
  flutter_speed_dial: ^7.0.0
  flutter_dotenv: ^5.2.1
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  syncfusion_flutter_pdf: ^34.1.29
  syncfusion_flutter_pdfviewer: ^34.1.29
  archive: ^4.0.7
  xml: ^7.0.1
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3

  # Google Sign-In
  google_sign_in: ^6.2.1

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # Navigation
  go_router: ^13.2.0

  # UI
  google_fonts: ^6.2.1
  gap: ^3.0.1

  # Local storage
  shared_preferences: ^2.5.3

  # Utils
  uuid: ^4.4.0
  intl: ^0.19.0
  logger: ^2.3.0
  file_selector: ^1.1.0
  share_plus: ^13.3.0
  qr_flutter: ^4.1.0
  gal: ^2.3.1
  webview_flutter: ^4.14.1
  flutter_displaymode: ^0.7.0
  mobile_scanner: ^7.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.10
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/illustrations/
    - assets/animations/


flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/scholar_blue_icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/scholar_blue_icon.png"

  remove_alpha_ios: true