// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3QzRF5PHzEkNMJq-Ps34dGJsrNyR63JU',
    appId: '1:1008839970601:android:4dbb4568f1b0d1914f7138',
    messagingSenderId: '1008839970601',
    projectId: 'scholarmind-b384c',
    storageBucket: 'scholarmind-b384c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDUd6KP436TbEuadB9-OqL7_w502KA0pU',
    appId: '1:1008839970601:ios:a1089382302968ab4f7138',
    messagingSenderId: '1008839970601',
    projectId: 'scholarmind-b384c',
    storageBucket: 'scholarmind-b384c.firebasestorage.app',
    iosClientId:
        '1008839970601-k717gn6krbfq1prehrjc3jscuadu300i.apps.googleusercontent.com',
    iosBundleId: 'com.scholarmind.scholarMind',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDUd6KP436TbEuadB9-OqL7_w502KA0pU',
    appId: '1:1008839970601:ios:a1089382302968ab4f7138',
    messagingSenderId: '1008839970601',
    projectId: 'scholarmind-b384c',
    storageBucket: 'scholarmind-b384c.firebasestorage.app',
    iosClientId:
        '1008839970601-k717gn6krbfq1prehrjc3jscuadu300i.apps.googleusercontent.com',
    iosBundleId: 'com.scholarmind.scholarMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANP83RUTJw_4JcwTTx-rFsTU81hENqK10',
    appId: '1:1008839970601:web:7ad0054e5508548e4f7138',
    messagingSenderId: '1008839970601',
    projectId: 'scholarmind-b384c',
    authDomain: 'scholarmind-b384c.firebaseapp.com',
    storageBucket: 'scholarmind-b384c.firebasestorage.app',
    measurementId: 'G-Z78883HPZC',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANP83RUTJw_4JcwTTx-rFsTU81hENqK10',
    appId: '1:1008839970601:web:6ac411b9f7c20a604f7138',
    messagingSenderId: '1008839970601',
    projectId: 'scholarmind-b384c',
    authDomain: 'scholarmind-b384c.firebaseapp.com',
    storageBucket: 'scholarmind-b384c.firebasestorage.app',
    measurementId: 'G-B8YVZ4G07C',
  );
}
